pom.xml
src/main/java/org/apache/flink/benchmark/full/SerializationFrameworkAllBenchmarks.java
src/main/java/org/apache/flink/benchmark/functions/BaseSourceWithKeyRange.java
src/main/scala/org/apache/flink/benchmark/functions/ScalaADTSource.scala

A follow-up PR for https://github.com/apache/flink/pull/12929, to measure performance impact of custom ADT Scala serializer. 
Results:
```
SerializationFrameworkMiniBenchmarks.serializerScalaADT  thrpt  custom   30  2506.848 ± 66.692  ops/ms
SerializationFrameworkMiniBenchmarks.serializerScalaADT  thrpt  kryo     30  450.202  ± 15.389  ops/ms
```
Implemented as a part of `full` benchmarks, so it will be excluded from the regular scheduled benchmarking suite runs, as it's too niche and specific. I also had to add a maven-scala-plugin to the build, as there is no easy way of emitting Scala sealed traits directly from Java.

[FLINK-18631] benchmark for scala ADT source

---

src/main/java/org/apache/flink/benchmark/FlinkEnvironmentContext.java
src/main/java/org/apache/flink/benchmark/RemoteChannelThroughputBenchmark.java
src/main/java/org/apache/flink/benchmark/UnalignedCheckpointTimeBenchmark.java

The results as below:
Benchmark                                                                                                                 Mode  Cnt     Score     Error   Units
UnalignedCheckpointBenchmark.unalignedCheckpointWithLocalChannel      thrpt   30  1985.953 ± 156.639  ops/ms
UnalignedCheckpointBenchmark.unalignedCheckpointWithRemoteChannel  thrpt   30  1327.177 ±  86.421  ops/ms

[FLINK-19003][checkpointing] Add micro-benchmark for unaligned checkpoints

---

pom.xml
src/main/java/org/apache/flink/benchmark/FlinkEnvironmentContext.java
src/main/java/org/apache/flink/benchmark/MultipleInputBenchmark.java
src/main/java/org/apache/flink/benchmark/operators/MultiplyByTwoOperatorFactory.java

```
Benchmark                                         Mode  Cnt      Score      Error   Units
MultipleInputBenchmark.multiInputMapSink         thrpt   15  13311.909 ± 1524.342  ops/ms
MultipleInputBenchmark.multiInputOneIdleMapSink  thrpt   15   7617.621 ±  262.473  ops/ms
```
Results are similar to two input benchmarks, with similar problem of quite large noise between iterations.

[FLINK-18905] Provide basic benchmarks for MultipleInputStreamOperator

---

src/main/java/org/apache/flink/benchmark/UnalignedCheckpointTimeBenchmark.java

This should fix the current benchmark time outing and will make the benchmark independent of any potential future default value changes.

[FLINK-19680] Explicitly set alignment timeout to 0 in the existing Unaligned Checkpoints benchmarks

---

pom.xml
src/main/java/org/apache/flink/scheduler/benchmark/JobConfiguration.java
src/main/java/org/apache/flink/scheduler/benchmark/SchedulerBenchmarkBase.java
src/main/java/org/apache/flink/scheduler/benchmark/SchedulerBenchmarkUtils.java
src/main/java/org/apache/flink/scheduler/benchmark/deploying/DeployingDownstreamTasksInBatchJobBenchmark.java
src/main/java/org/apache/flink/scheduler/benchmark/deploying/DeployingTasksBenchmarkBase.java
src/main/java/org/apache/flink/scheduler/benchmark/deploying/DeployingTasksInStreamingJobBenchmark.java
src/main/java/org/apache/flink/scheduler/benchmark/failover/FailoverBenchmarkBase.java
src/main/java/org/apache/flink/scheduler/benchmark/failover/RegionToRestartInBatchJobBenchmark.java
src/main/java/org/apache/flink/scheduler/benchmark/failover/RegionToRestartInStreamingJobBenchmark.java
src/main/java/org/apache/flink/scheduler/benchmark/partitionrelease/PartitionReleaseInBatchJobBenchmark.java
src/main/java/org/apache/flink/scheduler/benchmark/scheduling/InitSchedulingStrategyBenchmark.java
src/main/java/org/apache/flink/scheduler/benchmark/scheduling/SchedulingBenchmarkBase.java
src/main/java/org/apache/flink/scheduler/benchmark/scheduling/SchedulingDownstreamTasksInBatchJobBenchmark.java
src/main/java/org/apache/flink/scheduler/benchmark/topology/BuildExecutionGraphBenchmark.java

This pull request introduces several benchmarks to evaluate the performance of the scheduler. For now it includes four procedures:
- Topology building
- Scheduling
- Task deploying
- Calculating the tasks to restart when failover
- Partition releasing
All the topologies of the benchmarks consist of two vertices: one source vertex and one sink vertex. They are connected with all-to-all edges. The parallelisms of all vertices are 4k. There are two scenarios: 
- For the streaming job, the result partition type is `PIPELINED`, and the execution mode is `STREAMING`.
- For the batch job, the result partition type is `BLOCKING` , and the execution mode is `BATCH`.
It's worth noting that, for batch jobs, the sink tasks are scheduled and deployed if and only if all the source tasks finish. So the …

[FLINK-20612][runtime] Add benchmarks for scheduler

---

src/main/java/org/apache/flink/benchmark/StreamGraphUtils.java
src/main/java/org/apache/flink/scheduler/benchmark/JobConfiguration.java
src/main/java/org/apache/flink/scheduler/benchmark/SchedulerBenchmarkUtils.java
src/main/java/org/apache/flink/scheduler/benchmark/topology/BuildExecutionGraphBenchmark.java

The related changes are located at FLINK-21580 and FLINK-21347.

[FLINK-21625] Fix compilation errors due to the changes related to scheduler benchmarks

---

src/main/java/org/apache/flink/scheduler/benchmark/e2e/CreateSchedulerBenchmarkExecutor.java
src/main/java/org/apache/flink/scheduler/benchmark/e2e/SchedulingAndDeployingBenchmarkExecutor.java

This pull request introduces benchmarks to evaluate the performance of DefaultScheduler's creation, scheduling and deploying.
* Introduces benchmarks that evaluates the performance of creating DefaultScheduler.
* Introduces benchmarks that evaluates the performance of scheduling and deploying in DefaultScheduler.
For more details please check FLINK-21731.

[FLINK-21731] Add benchmarks for DefaultScheduler's creation, scheduling and deploying

---

README.md

"mvn -Dflink.version=1.11-SNAPSHOT clean install exec:exec", the first command in readme, does not compile because some symbolic errors.
In general, fixing to a certain version is very likely not going to work after a certain period of time. This can be really frustrating to users.
Remove the fixed version, and show how to add a flink versions in a later session.

[hotfix] Fix Readme instructions that are easy to break

---

src/main/java/org/apache/flink/scheduler/benchmark/SchedulerBenchmarkBase.java

It should be unnecessary to shut down the executor because as far as I can tell it isn't used.

[hotfix] Remove SchedulerBenchmark#teardown

---

src/main/java/org/apache/flink/benchmark/operators/RecordSource.java

In FLINK-23085, FutureUtils is moved from flink-runtime to flink-core. The reference in flink-benchmark should also be changed. The reference is located at: org/apache/flink/benchmark/operators/RecordSource.java.

[FLINK-23153] Fix the reference of FutureUtils in RecordSource

---

src/main/java/org/apache/flink/scheduler/benchmark/SchedulerBenchmarkExecutorBase.java
src/main/java/org/apache/flink/scheduler/benchmark/deploying/DeployingDownstreamTasksInBatchJobBenchmarkExecutor.java
src/main/java/org/apache/flink/scheduler/benchmark/deploying/DeployingTasksInStreamingJobBenchmarkExecutor.java
src/main/java/org/apache/flink/scheduler/benchmark/e2e/CreateSchedulerBenchmarkExecutor.java
src/main/java/org/apache/flink/scheduler/benchmark/e2e/SchedulingAndDeployingBenchmarkExecutor.java
src/main/java/org/apache/flink/scheduler/benchmark/failover/RegionToRestartInBatchJobBenchmarkExecutor.java
src/main/java/org/apache/flink/scheduler/benchmark/failover/RegionToRestartInStreamingJobBenchmarkExecutor.java
src/main/java/org/apache/flink/scheduler/benchmark/partitionrelease/PartitionReleaseInBatchJobBenchmarkExecutor.java
src/main/java/org/apache/flink/scheduler/benchmark/scheduling/InitSchedulingStrategyBenchmarkExecutor.java
src/main/java/org/apache/flink/scheduler/benchmark/scheduling/SchedulingDownstreamTasksInBatchJobBenchmarkExecutor.java
src/main/java/org/apache/flink/scheduler/benchmark/topology/BuildExecutionGraphBenchmarkExecutor.java

In FLINK-22988, TestUtils are ported from Scala to Java. However, `SchedulerBenchmarkBase` in flink-benchmark calls this method when each benchmark teardowns. This make SchedulerBenchmarks not compiling, as FLINK-23078 says. To solve this issue, we'd like to wrap `TestingUtils.defaultExecutor().shutdownNow()` into `SchedulerBenchmarkUtil`. If this method is changed in the future, its reference must be fixed, too. 
Furthermore, it's confusing to have `SchedulerBenchmarkBase` in both flink and flink-benchmark. So I'd like to propose change `SchedulerBenchmarkBase` into `SchedulerBenchmarkExecutorBase` in flink-benchmark.
* Change `TestingUtils.defaultExecutor().shutdownNow()` into `SchedulerBenchmarkUtil#shutdownTestingUtilDefaultExecutor`.

[FLINK-23078] Fix SchedulerBenchmarkExecutorBase#teardown

---

src/main/java/org/apache/flink/benchmark/BlockingPartitionBenchmark.java
src/main/java/org/apache/flink/benchmark/BlockingPartitionRemoteChannelBenchmark.java
src/main/java/org/apache/flink/benchmark/MemoryStateBackendBenchmark.java
src/main/java/org/apache/flink/benchmark/RocksStateBackendBenchmark.java
src/main/java/org/apache/flink/benchmark/UnalignedCheckpointTimeBenchmark.java
src/main/java/org/apache/flink/benchmark/WindowBenchmarks.java

Prevents an issue where `FlinkEnvironmentContext#setUp/tearDown` would be called multiple times, because subclasses contained overrides annotated with `@SetUp/@TearDown` which called into the parent version.
The effect can be easily seen by adding some `println` statements to `FlinkEnvironmentContext#setUp` and running the `WindowBenchmarks` (or any benchmark with a `FlinkEnvironmentContext` subclass).

[FLINK-23383] Prevent duplicate setUp/tearDown calls 

---

pom.xml

This fix current check when running benchmarks on the shaded jar package.

[FLINK-23398] Exclude signature files from shaded benchmarks.jar

---

pom.xml
src/main/java/org/apache/flink/benchmark/FlinkEnvironmentContext.java
src/main/java/org/apache/flink/benchmark/UnalignedCheckpointTimeBenchmark.java

Sets up a MiniCluster in the `FlinkEnvironmentContext`, which all jobs will be run against.

[FLINK-23392] Exclude startup/shutdown time from benchmarks

---

src/main/java/org/apache/flink/benchmark/ProcessingTimerBenchmark.java

This pull request adds a new benchmark for processing timers. 
Output example: 
```
Result "org.apache.flink.benchmark.ProcessingTimerBenchmark.fireProcessingTimers":
0.683 ±(99.9%) 0.010 ops/ms [Average]
(min, avg, max) = (0.659, 0.683, 0.730), stdev = 0.015
CI (99.9%): [0.673, 0.692] (assumes normal distribution)
Benchmark                                       Mode  Cnt  Score   Error   Units
ProcessingTimerBenchmark.fireProcessingTimers  thrpt   30  0.683 ± 0.010  ops/ms
Benchmark result is saved to jmh-result.csv
```

[FLINK-23208] Add a benchmark for processing timers

---

pom.xml
src/main/java/org/apache/flink/benchmark/BlockingPartitionBenchmark.java
src/main/java/org/apache/flink/benchmark/BlockingPartitionRemoteChannelBenchmark.java

Removes the scala suffix from the flink-runtime dependency, which is required because flink-runtime on master is now scala-free.
Because of the suffix the benchmarks were using an old snapshot test-jar, which referenced classes that no longer exist.
Note that CI may fail because Flink snapshots are currently broken.

[FLINK-23491] Update flink-runtime dependency

---

src/main/java/org/apache/flink/benchmark/ProcessingTimerBenchmark.java

Previous 1000 records was forced upon this benchmark because of
very slow production code. After resolving FLINK-23689 we can
safely increase number of records. Otherwise we would be testing
setup time of a Flink job.

[FLINK-23689] Increase ProcessingTimerBenchmark length

---

pom.xml

In Flink 1.15 we will drop scala 2.11. Therefore we should upgrade
benchmarks to scala 2.12 as well.

[hotfix] Upgrade to scala 2.12

---

jenkinsfiles/benchmark.jenkinsfile

The new universal jenkins parametrized script was created. 
The main difference compare to current scripts:
- Sending a message about successful build after all builds. Right now, this message is sent only for benchmark-request
- The one commit format for master and benchmark-request. Right now, benchmark-request format contains only flink commit while master build format contains flink commit, flink-benchmark commit and date.

[FLINK-25246] Added universal jenkins script to repository

---

src/main/java/org/apache/flink/benchmark/BlockingPartitionBenchmark.java
src/main/java/org/apache/flink/benchmark/BlockingPartitionRemoteChannelBenchmark.java

FLINK-25637 changed the default blocking shuffle implementation from hash-shuffle to sort-shuffle which caused some benchmark regression. This PR tries to fix the regression. For more information about the regression, please refer to https://issues.apache.org/jira/browse/FLINK-25704.

[FLINK-25704] Fix the blocking partition benchmark regression caused by FLINK-25637

---

src/main/java/org/apache/flink/state/benchmark/HashMapStateBackendRescalingBenchmarkExecutor.java
src/main/java/org/apache/flink/state/benchmark/RescalingBenchmarkBase.java
src/main/java/org/apache/flink/state/benchmark/RocksdbStateBackendRescalingBenchmarkExecutor.java

This pull request adds a benchmark for rescaling.
The benchmark process is:
(1) generate some states,
(2) change the parallelism of the operator, and restore from these states generate before.
The implementation of this benchmark is based on `RocksIncrementalCheckpointRescalingTest`, and **Average Time** is used to measure the rescaling performance on each subtask.
And the results of this benchmark are:
```text
Benchmark                                           (backendType)  (parallelism1)  (parallelism2)  (subtaskIndex)  Mode  Cnt    Score     Error  Units
RocksIncrementalCheckpointReScaleBenchmark.rescale           heap               3               4               0  avgt    3   17.326 ±   3.303  ms/op
RocksIncrementalCheckpointReScaleBenchmark.rescale           heap               3 …
```

[FLINK-23399][checkpoint] Add a benchmark for rescaling

---

src/main/java/org/apache/flink/state/benchmark/HashMapStateBackendRescalingBenchmarkExecutor.java
src/main/java/org/apache/flink/state/benchmark/RocksdbStateBackendRescalingBenchmarkExecutor.java

In `Iteration` level, `initializeState()` may be called repeatedly without setup, which causes build failed. So, change the level of `Setup/TearDown` in the rescaling benchmark from `Iteration` to `Invocation`.
Here is the exception message:
```
java.lang.IllegalStateException: TestHarness has already been initialized. Have you opened this harness before initializing it?
at org.apache.flink.util.Preconditions.checkState(Preconditions.java:193)
at org.apache.flink.streaming.util.AbstractStreamOperatorTestHarness.initializeState(AbstractStreamOperatorTestHarness.java:573)
at org.apache.flink.streaming.util.AbstractStreamOperatorTestHarness.initializeState(AbstractStreamOperatorTestHarness.java:466)
at org.apache.flink.contrib.streaming.state.benchmark.RescalingBenchmark.rescale(RescalingBenc …
```

[FLINK-27214] Fix rescaling benchmark build failed

---

regression_report.py
save_jmh_result.py

1. Add the script that updates fields for codespeed_benchmark table. After updating, the Y axis  would become “ms/op (less is better)”, e.g. [rescaleHeap](http://codespeed.dak8s.net:8000/timeline/#/?ben=rescaleHeap.RESCALE_IN&extr=on&quarts=on&equid=off&env=2&revs=200&exe=1,3,5,6,8,9)
2. Update save_jmh_results.py , If a new benchmark is introduced, the `lessisbetter` and `units` fields of results would be determined by a new benchmark instead of hard-code.
3. Update regression_report.py to detect the "less is better" regression.

[FLINK-27571][benchmark] Recognize 'less is better' benchmarks in regression detection script

---

jenkinsfiles/regression-check.jenkinsfile

Due to the[ limitation of the message length](https://github.com/jenkinsci/slack-plugin/issues/735#issuecomment-774131103) of slack plugin, the performance regressions notifications in Slack are cut off.  This PR replaces sending messages with sending attachments.

[FLINK-30870][benchmark] Replace sending slack messages with attachments

---

.github/workflows/ci.yml

CI failed (see https://github.com/apache/flink-benchmarks/actions/runs/4827826910/jobs/8602513410?pr=70), because `libssl1.0.0_1.0.2n-1ubuntu5.12_amd64.deb` has been replaced by [libssl1.0.0_1.0.2n-1ubuntu5.12_amd64.deb](http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.12_amd64.deb).

[hotfix] Fix libssl install failures

---

pom.xml

The benchmarks rely on the test jar of `flink-streaming-java`. However, the jar is set to test scope, thus not included in the packaged jar. Therefore ClassNotFoundException occurs while running the benchmarks with `java --jar xxx` command.
```
java.lang.NoClassDefFoundError: org/apache/flink/streaming/util/KeyedOneInputStreamOperatorTestHarness
at org.apache.flink.contrib.streaming.state.benchmark.RescalingBenchmark.prepareState(RescalingBenchmark.java:111)
at org.apache.flink.contrib.streaming.state.benchmark.RescalingBenchmark.setUp(RescalingBenchmark.java:78)
at org.apache.flink.state.benchmark.RocksdbStateBackendRescalingBenchmarkExecutor.setUp(RocksdbStateBackendRescalingBenchmarkExecutor.java:66)
at org.apache.flink.state.benchmark.generated.RocksdbStateBackendRescalingBenchmarkExec …
```

[FLINK-31965] Fix ClassNotFoundException in benchmarks

---

regression_report_v2.py

Avoid exceptions of `regression_report_v2.py` when data points are insufficient.

[FLINK-32244] Avoid exceptions of detecting script when data points are insufficient

---

.mvn/wrapper/maven-wrapper.properties
mvnw
mvnw.cmd

The actual code gives the following error:
```
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.4.0:add-source (scala-compile-first) on project benchmark: The plugin net.alchim31.maven:scala-maven-plugin:4.4.0 requires Maven version 3.3.9 -> [Help 1]
```
In this PR I've generated a wrapper for `3.3.9` as minimal version.

[FLINK-32415] Add maven wrapper to benchmark to avoid maven version issues

---

README.md
pom.xml

Flink has supported java 17, however, the benchmark does not support running with java 17 out of the box. The runner complains:
```
Caused by: java.lang.RuntimeException: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.Object[] java.util.Arrays$ArrayList.a accessible: module java.base does not "opens java.util" to unnamed module @14899482
01:39:16 at com.twitter.chill.java.ArraysAsListSerializer.<init>(ArraysAsListSerializer.java:69)
01:39:16 at org.apache.flink.api.java.typeutils.runtime.kryo.FlinkChillPackageRegistrar.registerSerializers(FlinkChillPackageRegistrar.java:67)
01:39:16 at org.apache.flink.api.java.typeutils.runtime.kryo.KryoSerializer.getKryoInstance(KryoSerializer.java:513)
01:39:16 at …
```

[FLINK-33161] Java17 profile for benchmarking

---

pom.xml
src/main/java/org/apache/flink/olap/benchmark/HighAvailabilityServiceBenchmark.java

This PR aims to add high availability service micro benchmark for olap. It will compare the throughputs for none and zookeeper ha service in dispatcher to show that, the current high availability service should be divided into cluster and job high availability services, which have been discussed in https://issues.apache.org/jira/browse/FLINK-32667. Then we can configure none ha service for job when cluster ha service is needed in flink cluster to improve the performance for olap jobs.
The main work of this PR include:
1. Create a `MiniCluster` with `ZOOKEEPER` and `NONE` high availability services.
2. Create a job with one no-op vertex
3. Count the throughput of submitting jobs per second
The results show that the throughput with none HA is more than twice that of zookeeper HA.

[FLINK-33033][olap][haservice] Add haservice micro benchmark for olap

---

jenkinsfiles/regression-check.jenkinsfile
regression_report.py
regression_report_v2.py

After [FLINK-33052](https://issues.apache.org/jira/browse/FLINK-33052), the codespeed and benchmark servers are hosted on Aliyun. This PR modifies the benchmark daily monitoring scripts for the new environment.

[FLINK-33482] Flink benchmark regression check in new machines hosted on Aliyun

---

src/main/java/org/apache/flink/benchmark/HighAvailabilityServiceBenchmark.java

To add it to the default benchmark bundle.

[hotfix] Relocate the HighAvailabilityServiceBenchmark

---

src/main/java/org/apache/flink/state/benchmark/StateBenchmarkBase.java
src/main/java/org/apache/flink/state/benchmark/StateBenchmarkConstants.java
src/main/java/org/apache/flink/state/benchmark/ttl/TtlListStateBenchmark.java
src/main/java/org/apache/flink/state/benchmark/ttl/TtlMapStateBenchmark.java
src/main/java/org/apache/flink/state/benchmark/ttl/TtlStateBenchmarkBase.java
src/main/java/org/apache/flink/state/benchmark/ttl/TtlValueStateBenchmark.java

As the title says, This PR introduce TTL state based benchmarks. The newly added tests are basically the same as the previous tests, but have been streamlined because the running time is too long with so many parameters.
I also suggest we disable it in the daily run, or only enable it weekly in jenkins since this is time-consuming.

[FLINK-30535] Introduce TTL state based benchmarks

---

src/main/java/org/apache/flink/benchmark/MultipleInputBenchmark.java

Due to this commit in main repo https://github.com/apache/flink/commit/41391065e1bf1476040039077049fbb98bec457e , there is a compilation error. This PR change to use another constructor of `MockSourceReader` to fix this.

[hotfix] Fix compilation error due to constructor removal of MockSourceReader

---

src/main/java/org/apache/flink/benchmark/MemoryStateBackendBenchmark.java
src/main/java/org/apache/flink/benchmark/RocksStateBackendBenchmark.java
src/main/java/org/apache/flink/benchmark/WindowBenchmarks.java
src/main/java/org/apache/flink/state/benchmark/ttl/TtlStateBenchmarkBase.java

Due to https://github.com/apache/flink/pull/25250 , the TTL builder using `org.apache.flink.api.common.time.Time` is removed. This PR fixes this.

[hotfix] Use `Duration` instead of `Time`

---

src/main/java/org/apache/flink/benchmark/SerializationFrameworkMiniBenchmarks.java
src/main/java/org/apache/flink/benchmark/full/SerializationFrameworkAllBenchmarks.java

A recent breaking change in Flink 2.0 (https://github.com/apache/flink/pull/25960) breaks compilation. This PR aims to fix that.

[FLINK-37115] Fix compile error related with SerializerConfig

---

pom.xml

Upgrading flink-shaded as the last step of flink-shaded release mentioned at
https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=85472039#Creatingaflinkshadedrelease-Deploysourceandbinaryreleasestodist.apache.org

[FLINK-37376] Upgrade flink-shaded to 20.0
